# File generated by the HLCI code
# 

Molecule name

0 1
C      1.07500      1.25000      0.00000
C      0.40500      2.41047      0.00000
H      0.58000      0.39263      0.00000
C      2.41500      1.25000      0.00000
C      1.07500      3.57095      0.00000
H     -0.58500      2.41047      0.00000
C      2.41500      3.57095      0.00000
H      0.58000      4.42831      0.00000
C      3.08500      2.41047      0.00000
H      2.91000      4.42831      0.00000
H      2.91000      0.39263      0.00000
H      4.07500      2.41047      0.00000

$nbo nrt $end
$NRTSTR
  STR        ! HuLis Wgt = 40.23% (HLP)  S1
    LONE END
    BOND D 1 2 D 4 9 D 5 7 S 1 3 S 1 4 S 2 5 S 2 6 S 4 11 S 5 8 S 7 9 S 7 10 S 9 12 END
  END
  STR        ! HuLis Wgt = 40.23% (HLP)  S2
    LONE END
    BOND D 1 4 D 2 5 D 7 9 S 1 2 S 1 3 S 2 6 S 4 9 S 4 11 S 5 7 S 5 8 S 7 10 S 9 12 END
  END
  STR        ! HuLis Wgt = 6.51% (HLP)  S3
    LONE END
    BOND D 2 5 D 4 9 S 1 2 S 1 3 S 1 4 S 1 7 S 2 6 S 4 11 S 5 7 S 5 8 S 7 9 S 7 10 S 9 12 END
  END
  STR        ! HuLis Wgt = 6.51% (HLP)  S4
    LONE END
    BOND D 1 2 D 7 9 S 1 3 S 1 4 S 2 5 S 2 6 S 4 5 S 4 9 S 4 11 S 5 7 S 5 8 S 7 10 S 9 12 END
  END
  STR        ! HuLis Wgt = 6.51% (HLP)  S5
    LONE END
    BOND D 1 4 D 5 7 S 1 2 S 1 3 S 2 5 S 2 6 S 2 9 S 4 9 S 4 11 S 5 8 S 7 9 S 7 10 S 9 12 END
  END
$END
